name: ci/cd

on:
  push:
    branches: [ main, release/*]
  pull_request:
    branches: [ main, release/*]

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [19, 20, 21, 22, 23, 24, 25]
        # otp_version: [22]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 lfe compile
    - name: Generate Releease
      run: rebar3 release
